development: &development
  adapter: mysql2
  database: ld28_development
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  database: ld28_development
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  database: ld28_test
  host: localhost
  username: root
  password:
