development:
  facebook_app_id: 118981661496259
  twitter_login: dekart1234
  google_analytics_id: UA-111105-32
  domain: fbdev2.railorz.com

production:
  facebook_app_id: 503281309769310
  twitter_login: dekart1234
  google_analytics_id: UA-111105-48
  domain: glacial-taiga-5985.herokuapp.com
